# Site settings
title: Lie209's Blog
SEOTitle: 李德鑫的个人博客
header-img: img/post-bg-desk.jpg
email: lie209@qq.com
description: "Every failure is leading towards success."
keyword: "java,Linux,李德鑫，李德鑫的博客，Lie209"
url: "http://lie209.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lie209/lie209.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "普通的改变，将改变普通"
sidebar-avatar: /img/about-lie209.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:    
zhihu_username:     lie209
github_username:    lie209
facebook_username:  lie209
jianshu_username:   
twitter_username:  lie209lidexin   



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 14c1fbbb95f3faa2dd3d                          #生成的clientID
  clientSecret: 13e78dbc795f4f2c1c26be74a52789fb5749f2c5    #生成的clientSecret
  repo: lie209.github.io    #仓库名称
  owner: lie209    #github用户名
  admin: lie209
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 0cb0515004305eec21702e554e462dbe

# Google Analytics
ga_track_id: 'UA-129023232-1'            # Format: UA-xxxxxx-xx
ga_domain: lie209.tech               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "百度",
        href: "http://baidu.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Java Documentation",
        href: "https://docs.oracle.com/en/java/"
    }
]
